### ISSUE TITLE
Unsupported French Accents

### ISSUE THREAD

**Issue by adocquin** [OlegLustenko/language-4GL-atom#1]
Hello,

Is it possible to add compatibility with French accents please?

Regards,

**Comment by OlegLustenko** [comment]
Hi @adocquin could you provide minimal example which includes

current result:
and expect result:

**Comment by adocquin** [comment]
Hi @OlegLustenko, thank you for your quick answer.
Here are some examples of the results obtained when I load files edited in Atom in Genero:

![example](https://user-images.githubusercontent.com/14333313/28520758-17ea7ff4-7071-11e7-8026-6cc29a771fa0.png)

And here is the except result:

![example-excepted](https://user-images.githubusercontent.com/14333313/28520847-7ad98394-7071-11e7-941f-eaef5daefc9b.png)

Do not hesitate to tell me if you need further information.

**Comment by OlegLustenko** [comment]
closing due to innactivity
